name: Cloudflare Temporary Tunnel Test

on: 
  workflow_dispatch: # دستی اجراش کن که سورپرایز نشی

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Install dependencies and Xray
        run: |
          echo "📦 Installing dependencies (unzip, wget)..."
          sudo apt update && sudo apt install -y unzip  wget > /dev/null 2>&1

          # --- ۲. نصب Xray (نسخه 64 بیتی بهینه) ---
          if [ ! -f "/usr/local/bin/xray" ]; then
              echo "📥 Downloading Xray Core..."
              wget -q https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip
              sudo unzip -q -o Xray-linux-64.zip -d /usr/local/bin/xray
              sudo chmod +x /usr/local/bin/xray/xray
              ls -al /usr/local/bin/xray
              rm Xray-linux-64.zip
              echo "✅ Xray Installed."
          else
              echo "✔ Xray is already there."
          fi

      - name: Execute shell script
        run: chmod +x xray.sh && ./xray.sh

      - name: Install and Run Cloudflare Tunnel
        run: |
           # دانلود کردن کلودفلر (نسخه لینوکس)
           wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
           sudo dpkg -i cloudflared-linux-amd64.deb

           # اجرای تونل به صورت موقت و استخراج URL
           # این قسمت یکم جادویی کار می‌کنه چون خروجی رو توی لاگ نشون میده
            echo "Starting Cloudflare Tunnel..."
            cloudflared tunnel --url http://localhost:8888 --logfile tunnel.log &
          
           # یه چند ثانیه صبر کنیم که کلودفلر بتونه با دنیا ارتباط برقرار کنه
           sleep 10
          
           # حالا بریم دنبال اون آدرس خوشگله بگردیم که به .trycloudflare.com ختم میشه
           TUNNEL_URL=$(grep -o 'https://[-a-z0-9.]*\.trycloudflare\.com' tunnel.log | head -n 1)
          
           echo "------------------------------------------------"
           echo "بفرما! آدرس تونل شما با احترام تقدیم می‌شود:"
           echo "URL: $TUNNEL_URL"
           echo "------------------------------------------------"


         
           TOTAL_TIME=$((5 * 60 * 60))   # 5 ساعت به ثانیه
           INTERVAL=300                 # 5 دقیقه به ثانیه
           elapsed=0
           while [ $elapsed -lt $TOTAL_TIME ]; do
             echo "Tunnel is alive and kicking! ⏳ Elapsed minutes: $((elapsed / 60)) / 300"
             sleep $INTERVAL
           elapsed=$((elapsed + INTERVAL))
           done

